### ISSUE TITLE
Problem with heads

### ISSUE THREAD

**Issue by assasin541** [CobbleSword/NachoSpigot#14]
Player heads in guis are bugged

**Comment by DeadSteve51** [comment]
Dont use nacho it isn't stable

**Comment by assasin541** [comment]
@DeadSteve51 what do you recommend to use?

**Comment by CyberFlameGO** [comment]
I think @Lucaskyy fixed this, @HeathLoganCampbell you’re good to close this

**Comment by andreasdc** [comment]
@CyberFlameGO I didn't find proper fix for this issue.

**Comment by CyberFlameGO** [comment]
@andreasdc We merged Lucas’ fork to upstream, and if I’m not mistaken, it’s fixed in that fork. Please let me know if it isn’t :)

**Comment by andreasdc** [comment]
@CyberFlameGO I don't see any fix to this bug.

**Comment by CyberFlameGO** [comment]
I think it’s this? `[SportPaper-0027] Fix head rotation packet spam`
I could be wrong though (in that it’s not fixed)

**Comment by andreasdc** [comment]
@CyberFlameGO then it's not fixed. When you have guis with player heads (setOwner) it appears as the same skin/head.

**Comment by Lucaskyy** [comment]
Ah no, that is not the fix for that. I will try to reproduce this soon and get a fix for it.

**Comment by Lucaskyy** [comment]
@andreasdc "with the same skin/head" you mean Steve/Alex skin?

**Comment by andreasdc** [comment]
@Lucaskyy it gets first shown player head, but it doesn't happen in all types of guis.

**Comment by andreasdc** [comment]
@Lucaskyy maybe it's because I don't create new SkullMeta for this type of gui, but I use old one and change displayname and owner?

**Comment by Lucaskyy** [comment]
Create a new SkullMeta and set it to the ItemStack. Don't reuse it.

Try this :)

**Comment by andreasdc** [comment]
@Lucaskyy I will try that today. :) It worked on taco etc. before.

**Comment by andreasdc** [comment]
@Lucaskyy btw. good job on updating, you can look on other issues and look for improvements from other projects too. Keep up the good work! 🥇 ❤️

**Comment by Lucaskyy** [comment]
> @Lucaskyy btw. good job on updating, you can look on other issues and look for improvements from other projects too. Keep up the good work! 🥇 ❤️ 

Thank you! :) And yes, I will.

**Comment by DeadSteve51** [comment]
Nacho comeback?

**Comment by DeadSteve51** [comment]
Someone should close this

**Comment by CyberFlameGO** [comment]
Turns out this doesn’t need closing yet :)

**Comment by Lucaskyy** [comment]
By the way, if you can;

Could you send me your code that is having issues with NachoSpigot so I can try it out locally.

**Comment by andreasdc** [comment]
@Lucaskyy can you give me the discord?

**Comment by CyberFlameGO** [comment]
Take a look at the README.md on this repository, it’s there already

**Comment by Lucaskyy** [comment]
This seems to be more of a plugin issue than a NachoSpigot issue.

Re-using ItemStacks doesn't seem to work when using SkullMeta's. Is that normal MC behavior?

Please re-open this issue if you know what the issue could be behind this!

**Comment by Lucaskyy** [comment]
After some time taking a look, I noticed that this seems to be a Spigot or TacoSpigot issue. They have modified the TileEntitySkull and made some changes, which means I can't really go back to that since I don't have the old source code to see what got changed. My best bet for now is, don't reuse the ItemStacks when using SkullMeta's.

When I get some time, I might take a look at this to fix it.

**Comment by Lucaskyy** [comment]
Wanted to note, that if I recall correctly this issue has been fixed a couple weeks ago. So please try again using the latest version!

**Comment by andreasdc** [comment]
> Wanted to note, that if I recall correctly this issue has been fixed a couple weeks ago. So please try again using the latest version!

It's kind of fixed yes. :)
